repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
    args: [--contrib=CT1, --ignore=B6, --msg-filename]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
  - id: forbid-binary
  - id: markdownlint
