[book]
authors = ["Arthur Targaryen <dev@arthur.targaryen.email>"]
language = "en"
multilingual = false
src = "src"
title = "Knowledge"
description = "Knowledge I acquired."

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/arthur-targaryen/knowledge"

[output.html.print]
enable = false
